ARDUINO_DIR  = /usr/share/arduino
USER_LIB_PATH = /home/code/
TARGET       = power_meter
ARDUINO_LIBS = LiquidCrystal EEPROM
BOARD_TAG    = uno
MONITOR_PORT = /dev/ttyUSB0


include /usr/share/arduino/Arduino.mk
