[platformio]
src_dir = .
default_envs = uno

[env:uno]
platform = atmelavr
board = uno
framework = arduino
lib_deps = arduino-libraries/LiquidCrystal@^1.0.7
build_src_filter = +<*.cpp>

[env:native]
platform = native
test_framework = unity
test_build_src = yes
build_src_filter = +<pm1_protocol.cpp>
