#define LED_PIN 13
#define VOLTAGE_PIN 1

#define LIQUID_CRYSTAL_ARGS 8, 9, 4, 5, 6, 7
#define BACKLIGHT_PIN 10
#define BUTTONS_PIN 0

#define SENSOR_PERIOD_MILLIS 100
#define LOAD_CURRENT_PIN 1
#define LOAD_VOLTAGE_PIN 2