#include "screen_info.h"
#include <Arduino.h>
#include <LittleFS.h>
#include "build_time.h" // Dynamically generated by PlatformIO
#include <time.h>
#include "network/network_manager.h"
#include "ui_theme.h"

namespace screen_info {
namespace {

lv_obj_t* uptimeLabel = nullptr;
lv_obj_t* timeLabel = nullptr;
lv_obj_t* dateLabel = nullptr;
lv_obj_t* staIpLabel = nullptr;
lv_obj_t* apIpLabel = nullptr;
lv_obj_t* storagePercentLabel = nullptr;
lv_timer_t* updateTimer = nullptr;
uint8_t rowIndex = 0;

lv_obj_t* addRow(lv_obj_t* parent, const char* key, const char* value) {
    lv_obj_t* row = lv_obj_create(parent);

    // Strip default theme background, borders, and scrollbars
    // to utilize the object purely as a flex layout container
    lv_obj_remove_style_all(row);

    lv_obj_set_size(row, lv_pct(100), LV_SIZE_CONTENT);
    lv_obj_set_flex_flow(row, LV_FLEX_FLOW_ROW);
    lv_obj_set_style_pad_hor(row, 6, 0);
    lv_obj_set_style_pad_ver(row, 3, 0);
    lv_obj_set_flex_align(row, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    if (rowIndex++ & 1U) {
        lv_obj_set_style_bg_color(row, ui_theme::surfaceAlt(), 0);
        lv_obj_set_style_bg_opa(row, LV_OPA_COVER, 0);
    }

    lv_obj_t* keyLabel = lv_label_create(row);
    lv_label_set_text(keyLabel, key);
    lv_obj_set_style_text_color(keyLabel, ui_theme::mutedText(), 0);
    lv_obj_set_width(keyLabel, lv_pct(45));

    lv_obj_t* valLabel = lv_label_create(row);
    lv_label_set_text(valLabel, value);
    lv_obj_set_width(valLabel, lv_pct(55));

    return valLabel;
}

void formatUptime(char* buf, size_t len) {
    uint32_t s = millis() / 1000;
    snprintf(buf, len, "%luh %02lum %02lus",
              (unsigned long)(s / 3600), (unsigned long)((s % 3600) / 60), (unsigned long)(s % 60));
}

void updateCb(lv_timer_t*) {
    char buf[64];

    // Frequently changing status values.
    formatUptime(buf, sizeof(buf));
    lv_label_set_text(uptimeLabel, buf);

    // Wall Clock Time Update
    time_t now;
    struct tm timeinfo;
    time(&now);
    localtime_r(&now, &timeinfo);

    // Check if NTP has synchronized (year will be > 1970)
    if (timeinfo.tm_year > 70) {
        strftime(buf, sizeof(buf), "%I:%M:%S %p", &timeinfo);
        lv_label_set_text(timeLabel, buf);
    } else {
        lv_label_set_text(timeLabel, "-");
    }
    if (timeinfo.tm_year > 70) {
        strftime(buf, sizeof(buf), "%b %e %Y", &timeinfo);
        lv_label_set_text(dateLabel, buf);
    } else {
        lv_label_set_text(dateLabel, "-");
    }

    lv_label_set_text(staIpLabel, network_manager::getStaIpAddress());
    lv_label_set_text(apIpLabel, network_manager::isApEnabled() ? network_manager::getApIpAddress() : "Off");

    const size_t totalStorage = LittleFS.totalBytes();
    if (totalStorage == 0) {
        lv_label_set_text(storagePercentLabel, "-");
    } else {
        snprintf(buf, sizeof(buf), "%u%%", (unsigned)((LittleFS.usedBytes() * 100U) / totalStorage));
        lv_label_set_text(storagePercentLabel, buf);
    }
}

} // namespace

lv_obj_t* create(lv_obj_t* parent) {
    lv_obj_t* scr = lv_obj_create(parent);
    ui_theme::styleScreen(scr, 4);
    lv_obj_set_flex_flow(scr, LV_FLEX_FLOW_COLUMN);

    lv_obj_t* list = lv_obj_create(scr);
    ui_theme::styleCard(list, 2);
    lv_obj_set_size(list, lv_pct(100), LV_SIZE_CONTENT);
    lv_obj_set_flex_flow(list, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_style_pad_row(list, 0, 0);
    lv_obj_set_scrollbar_mode(list, LV_SCROLLBAR_MODE_OFF);

    rowIndex = 0;
    uptimeLabel  = addRow(list, "Uptime", "--");
    dateLabel    = addRow(list, "Date", "--");
    timeLabel    = addRow(list, "Time", "--");
    char build[96];
    snprintf(build, sizeof(build), "v%s", BUILD_VERSION);
    addRow(list, "Build", build);
    addRow(list, "Build Date", BUILD_DATE);
    addRow(list, "Build Time", BUILD_TIME);
    storagePercentLabel = addRow(list, "Data storage", "--");
    staIpLabel = addRow(list, "Station IP", "--");
    apIpLabel = addRow(list, "AP IP", "--");

    if(!updateTimer) {
        updateTimer = lv_timer_create(updateCb, 1000, nullptr);
    }
    updateCb(nullptr);

    return scr;
}

} // namespace screen_info
