#include "device_info_screen.h"
#include <Arduino.h>
#include "build_time.h" // Dynamically generated by PlatformIO
#include <time.h>
#include "network/internet_update_service.h"
#include "network/network_manager.h"
#include "../../theme/ui_theme.h"

namespace device_info_screen {
namespace {

lv_obj_t* uptimeLabel = nullptr;
lv_obj_t* timeLabel = nullptr;
lv_obj_t* dateLabel = nullptr;
lv_obj_t* staIpLabel = nullptr;
lv_obj_t* apIpLabel = nullptr;
lv_obj_t* staIpKeyLabel = nullptr;
lv_obj_t* apIpKeyLabel = nullptr;
lv_obj_t* updateDateLabel = nullptr;
lv_obj_t* updateStateLabel = nullptr;
lv_obj_t* updateDetailLabel = nullptr;
lv_obj_t* updateProgress = nullptr;
lv_obj_t* checkButton = nullptr;
lv_obj_t* installButton = nullptr;
lv_obj_t* automaticSwitch = nullptr;
lv_timer_t* updateTimer = nullptr;
uint8_t rowIndex = 0;

lv_obj_t* addRow(lv_obj_t* parent, const char* key, const char* value,
                 lv_obj_t** keyOut = nullptr) {
    lv_obj_t* row = lv_obj_create(parent);

    // Strip default theme background, borders, and scrollbars
    // to utilize the object purely as a flex layout container
    lv_obj_remove_style_all(row);

    lv_obj_set_size(row, lv_pct(100), LV_SIZE_CONTENT);
    lv_obj_set_flex_flow(row, LV_FLEX_FLOW_ROW);
    lv_obj_set_style_pad_hor(row, 6, 0);
    lv_obj_set_style_pad_ver(row, 3, 0);
    lv_obj_set_flex_align(row, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    if (rowIndex++ & 1U) {
        lv_obj_set_style_bg_color(row, ui_theme::surfaceAlt(), 0);
        lv_obj_set_style_bg_opa(row, LV_OPA_COVER, 0);
    }

    lv_obj_t* keyLabel = lv_label_create(row);
    if (keyOut) *keyOut = keyLabel;
    lv_label_set_text(keyLabel, key);
    lv_obj_set_style_text_color(keyLabel, ui_theme::mutedText(), 0);
    lv_obj_set_width(keyLabel, lv_pct(45));

    lv_obj_t* valLabel = lv_label_create(row);
    lv_label_set_text(valLabel, value);
    lv_obj_set_width(valLabel, lv_pct(55));

    return valLabel;
}

void formatUptime(char* buf, size_t len) {
    uint32_t s = millis() / 1000;
    snprintf(buf, len, "%luh %02lum %02lus",
              (unsigned long)(s / 3600), (unsigned long)((s % 3600) / 60), (unsigned long)(s % 60));
}

const char* updateStateText(internet_update_service::State state) {
    switch (state) {
        case internet_update_service::State::Idle: return "Ready";
        case internet_update_service::State::WaitingForNetwork: return "Waiting for Internet";
        case internet_update_service::State::WaitingForTime: return "Waiting for time";
        case internet_update_service::State::Checking: return "Checking...";
        case internet_update_service::State::UpToDate: return "Up to date";
        case internet_update_service::State::Available: return "Update available";
        case internet_update_service::State::Downloading: return "Downloading";
        case internet_update_service::State::Verifying: return "Verifying...";
        case internet_update_service::State::Rebooting: return "Restarting...";
        case internet_update_service::State::Failed: return "Check failed";
        case internet_update_service::State::BlockedAfterRollback: return "Update blocked";
    }
    return "Ready";
}

void updateCb(lv_timer_t* timer) {
    if (timer && timer->user_data && !lv_obj_is_visible(static_cast<lv_obj_t*>(timer->user_data))) return;
    char buf[64];

    // Frequently changing status values.
    formatUptime(buf, sizeof(buf));
    lv_label_set_text(uptimeLabel, buf);

    // Wall Clock Time Update
    time_t now;
    struct tm timeinfo;
    time(&now);
    localtime_r(&now, &timeinfo);

    // Check if NTP has synchronized (year will be > 1970)
    if (timeinfo.tm_year > 70) {
        strftime(buf, sizeof(buf), "%I:%M:%S %p", &timeinfo);
        lv_label_set_text(timeLabel, buf);
    } else {
        lv_label_set_text(timeLabel, "-");
    }
    if (timeinfo.tm_year > 70) {
        strftime(buf, sizeof(buf), "%b %e %Y", &timeinfo);
        lv_label_set_text(dateLabel, buf);
    } else {
        lv_label_set_text(dateLabel, "-");
    }
    const char* stationSsid = network_manager::getCurrentSsid();
    snprintf(buf, sizeof(buf), "IP Address\n(%s)",
             stationSsid && stationSsid[0] ? stationSsid : "Station");
    lv_label_set_text(staIpKeyLabel, buf);
    lv_label_set_text(staIpLabel, network_manager::getStaIpAddress());
    const char* apSsid = network_manager::getCurrentApSsid();
    snprintf(buf, sizeof(buf), "IP Address\n(%s)",
             apSsid && apSsid[0] ? apSsid : "Access Point");
    lv_label_set_text(apIpKeyLabel, buf);
    lv_label_set_text(apIpLabel, network_manager::isApEnabled() ? network_manager::getApIpAddress() : "Off");

    internet_update_service::Status update{};
    if (internet_update_service::getStatus(update)) {
        if (update.updateDateUnixSeconds > 0) {
            time_t updated = static_cast<time_t>(update.updateDateUnixSeconds);
            struct tm updatedTime{};
            localtime_r(&updated, &updatedTime);
            strftime(buf, sizeof(buf), "%b %e %Y", &updatedTime);
            lv_label_set_text(updateDateLabel, buf);
        } else {
            lv_label_set_text(updateDateLabel, "-");
        }
        if (update.state == internet_update_service::State::Downloading) {
            snprintf(buf, sizeof(buf), "Downloading %u%%", update.progressPercent);
            lv_label_set_text(updateStateLabel, buf);
            lv_bar_set_value(updateProgress, update.progressPercent, LV_ANIM_OFF);
            lv_obj_clear_flag(updateProgress, LV_OBJ_FLAG_HIDDEN);
        } else {
            lv_label_set_text(updateStateLabel, updateStateText(update.state));
            lv_obj_add_flag(updateProgress, LV_OBJ_FLAG_HIDDEN);
        }
        if (update.error[0]) {
            lv_label_set_text(updateDetailLabel, update.error);
        } else if (update.availableVersion[0]) {
            snprintf(buf, sizeof(buf), "Version %s is available.",
                     update.availableVersion);
            lv_label_set_text(updateDetailLabel, buf);
        } else if (update.lastCheckUnixSeconds > 0) {
            time_t checked = static_cast<time_t>(update.lastCheckUnixSeconds);
            struct tm checkedTime{};
            localtime_r(&checked, &checkedTime);
            strftime(buf, sizeof(buf), "Last checked %b %e, %I:%M %p", &checkedTime);
            lv_label_set_text(updateDetailLabel, buf);
        } else {
            lv_label_set_text(updateDetailLabel, "Not checked yet.");
        }
        if (update.busy) lv_obj_add_state(checkButton, LV_STATE_DISABLED);
        else lv_obj_clear_state(checkButton, LV_STATE_DISABLED);
        if (update.state == internet_update_service::State::Available) {
            lv_obj_clear_flag(installButton, LV_OBJ_FLAG_HIDDEN);
        } else {
            lv_obj_add_flag(installButton, LV_OBJ_FLAG_HIDDEN);
        }
        const bool checked =
            lv_obj_has_state(automaticSwitch, LV_STATE_CHECKED);
        if (checked != update.automatic) {
            if (update.automatic) lv_obj_add_state(automaticSwitch, LV_STATE_CHECKED);
            else lv_obj_clear_state(automaticSwitch, LV_STATE_CHECKED);
        }
    }
}

void checkEvent(lv_event_t*) {
    internet_update_service::requestCheck();
}

void installEvent(lv_event_t*) {
    internet_update_service::requestInstall();
}

void automaticEvent(lv_event_t*) {
    internet_update_service::setAutomatic(
        lv_obj_has_state(automaticSwitch, LV_STATE_CHECKED));
}

} // namespace

lv_obj_t* create(lv_obj_t* parent) {
    lv_obj_t* scr = lv_obj_create(parent);
    ui_theme::styleScreen(scr, 4);
    lv_obj_set_flex_flow(scr, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(scr, LV_FLEX_ALIGN_SPACE_BETWEEN,
                          LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

    lv_obj_t* list = lv_obj_create(scr);
    ui_theme::styleCard(list, 2);
    lv_obj_set_size(list, lv_pct(100), LV_SIZE_CONTENT);
    lv_obj_set_flex_flow(list, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_style_pad_row(list, 0, 0);
    lv_obj_set_scrollbar_mode(list, LV_SCROLLBAR_MODE_OFF);

    rowIndex = 0;
    uptimeLabel  = addRow(list, "Uptime", "--");
    dateLabel    = addRow(list, "Date", "--");
    timeLabel    = addRow(list, "Time", "--");
    staIpLabel = addRow(list, "IP Address\n(Station)", "--", &staIpKeyLabel);
    apIpLabel = addRow(list, "IP Address\n(Access Point)", "--", &apIpKeyLabel);

    lv_obj_t* updateCard = lv_obj_create(scr);
    ui_theme::styleCard(updateCard, 6);
    lv_obj_set_width(updateCard, lv_pct(100));
    lv_obj_set_height(updateCard, LV_SIZE_CONTENT);
    lv_obj_set_flex_flow(updateCard, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_style_pad_row(updateCard, 4, 0);

    lv_obj_t* updateHeader = lv_obj_create(updateCard);
    lv_obj_remove_style_all(updateHeader);
    lv_obj_set_size(updateHeader, lv_pct(100), LV_SIZE_CONTENT);
    lv_obj_set_flex_flow(updateHeader, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(updateHeader, LV_FLEX_ALIGN_SPACE_BETWEEN,
                          LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(lv_label_create(updateHeader), "Software update");
    updateStateLabel = lv_label_create(updateHeader);
    lv_label_set_text(updateStateLabel, "Ready");
    lv_obj_set_style_text_color(updateStateLabel, ui_theme::mutedText(), 0);

    lv_obj_t* updateDetails = lv_obj_create(updateCard);
    lv_obj_remove_style_all(updateDetails);
    lv_obj_set_size(updateDetails, lv_pct(100), LV_SIZE_CONTENT);
    lv_obj_set_flex_flow(updateDetails, LV_FLEX_FLOW_COLUMN);
    rowIndex = 0;
    char build[96];
    snprintf(build, sizeof(build), "v%s", BUILD_VERSION);
    addRow(updateDetails, "Version", build);
    addRow(updateDetails, "Build Date", BUILD_DATE);
    updateDateLabel = addRow(updateDetails, "Update Date", "-");

    updateDetailLabel = lv_label_create(updateCard);
    lv_obj_set_width(updateDetailLabel, lv_pct(100));
    lv_obj_set_style_text_color(updateDetailLabel, ui_theme::mutedText(), 0);
    updateProgress = lv_bar_create(updateCard);
    lv_obj_set_width(updateProgress, lv_pct(100));
    lv_bar_set_range(updateProgress, 0, 100);
    lv_obj_add_flag(updateProgress, LV_OBJ_FLAG_HIDDEN);

    lv_obj_t* automaticRow = lv_obj_create(updateCard);
    lv_obj_remove_style_all(automaticRow);
    lv_obj_set_size(automaticRow, lv_pct(100), LV_SIZE_CONTENT);
    lv_obj_set_flex_flow(automaticRow, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(automaticRow, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_pad_column(automaticRow, 8, 0);
    automaticSwitch = lv_switch_create(automaticRow);
    lv_obj_add_event_cb(automaticSwitch, automaticEvent, LV_EVENT_VALUE_CHANGED, nullptr);
    lv_obj_t* automaticLabel = lv_label_create(automaticRow);
    lv_label_set_text(automaticLabel, "Install updates automatically");
    lv_obj_set_flex_grow(automaticLabel, 1);
    lv_label_set_long_mode(automaticLabel, LV_LABEL_LONG_WRAP);

    lv_obj_t* actions = lv_obj_create(updateCard);
    lv_obj_remove_style_all(actions);
    lv_obj_set_size(actions, lv_pct(100), LV_SIZE_CONTENT);
    lv_obj_set_flex_flow(actions, LV_FLEX_FLOW_ROW);
    lv_obj_set_style_pad_column(actions, 6, 0);
    checkButton = lv_btn_create(actions);
    lv_obj_set_flex_grow(checkButton, 1);
    ui_theme::stylePrimaryButton(checkButton);
    lv_obj_add_event_cb(checkButton, checkEvent, LV_EVENT_CLICKED, nullptr);
    lv_obj_t* checkLabel = lv_label_create(checkButton);
    lv_label_set_text(checkLabel, LV_SYMBOL_REFRESH " Check now");
    lv_obj_center(checkLabel);
    installButton = lv_btn_create(actions);
    lv_obj_set_flex_grow(installButton, 1);
    lv_obj_add_event_cb(installButton, installEvent, LV_EVENT_CLICKED, nullptr);
    lv_obj_t* installLabel = lv_label_create(installButton);
    lv_label_set_text(installLabel, "Install");
    lv_obj_center(installLabel);
    lv_obj_add_flag(installButton, LV_OBJ_FLAG_HIDDEN);

    lv_obj_t* projectInfo = lv_obj_create(updateCard);
    lv_obj_remove_style_all(projectInfo);
    lv_obj_set_size(projectInfo, lv_pct(100), LV_SIZE_CONTENT);
    lv_obj_set_flex_flow(projectInfo, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_style_pad_row(projectInfo, 2, 0);

    lv_obj_t* repositoryLabel = lv_label_create(projectInfo);
    lv_obj_set_width(repositoryLabel, lv_pct(100));
    lv_obj_set_style_text_font(repositoryLabel, &lv_font_montserrat_12, 0);
    lv_obj_set_style_text_color(repositoryLabel, ui_theme::accent(), 0);
    lv_label_set_text(repositoryLabel, "GitHub: https://github.com/camlee/power-meter");

    lv_obj_t* contactLabel = lv_label_create(projectInfo);
    lv_obj_set_width(contactLabel, lv_pct(100));
    lv_obj_set_style_text_font(contactLabel, &lv_font_montserrat_12, 0);
    lv_obj_set_style_text_color(contactLabel, ui_theme::mutedText(), 0);
    lv_label_set_text(contactLabel, "Contact: cam.w.lee@gmail.com");

    if(!updateTimer) {
        updateTimer = lv_timer_create(updateCb, 1000, scr);
    }
    if (lv_obj_is_visible(scr)) updateCb(nullptr);

    return scr;
}

} // namespace device_info_screen
