#!/usr/bin/env python3
"""Build the SPA and turn its gzipped assets into flash-resident C++ data.

This is a local developer/release check, deliberately not CI infrastructure.
PlatformIO invokes it before compiling firmware; `--verify` checks an already
generated table and enforces the published flash budget without changing files.
"""

from __future__ import annotations

import argparse
import gzip
import hashlib
import mimetypes
import os
import shutil
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
WEB = ROOT / "web"
DIST = WEB / "dist"
OUT_H = ROOT / "src" / "network" / "web_assets.generated.h"
OUT_CPP = ROOT / "src" / "network" / "web_assets.generated.cpp"
MAX_COMPRESSED_BYTES = 256 * 1024


def run_build() -> None:
    if not shutil.which("npm"):
        raise SystemExit("web assets require npm; install Node.js 20+ and rerun")
    if not (WEB / "node_modules").is_dir():
        subprocess.run(["npm", "ci"], cwd=WEB, check=True)
    subprocess.run(["npm", "run", "build"], cwd=WEB, check=True)


def asset_type(path: Path) -> str:
    if path.suffix == ".js":
        return "text/javascript; charset=utf-8"
    if path.suffix == ".css":
        return "text/css; charset=utf-8"
    if path.suffix == ".html":
        return "text/html; charset=utf-8"
    return mimetypes.guess_type(path.name)[0] or "application/octet-stream"


def collect_assets() -> list[tuple[str, str, bytes, bool, str]]:
    if not DIST.is_dir():
        raise SystemExit("web/dist is missing; run npm run build in esp32-viewe/web")
    assets = []
    for path in sorted(item for item in DIST.rglob("*") if item.is_file()):
        route = "/" + path.relative_to(DIST).as_posix()
        compressed = gzip.compress(path.read_bytes(), compresslevel=9, mtime=0)
        immutable = path.name != "index.html"
        etag = hashlib.sha256(compressed).hexdigest()[:16]
        assets.append((route, asset_type(path), compressed, immutable, etag))
    if not any(route == "/index.html" for route, *_ in assets):
        raise SystemExit("Vite did not produce index.html")
    total = sum(len(data) for _, _, data, _, _ in assets)
    if total > MAX_COMPRESSED_BYTES:
        raise SystemExit(f"compressed web bundle is {total} bytes; budget is {MAX_COMPRESSED_BYTES}")
    return assets


def cpp_bytes(data: bytes) -> str:
    lines = []
    for start in range(0, len(data), 16):
        lines.append("    " + ", ".join(f"0x{value:02x}" for value in data[start:start + 16]) + ",")
    return "\n".join(lines)


def generate(assets: list[tuple[str, str, bytes, bool, str]]) -> tuple[str, str]:
    build_id = hashlib.sha256(b"".join(data for _, _, data, _, _ in assets)).hexdigest()[:16]
    header = """// Generated by tools/build_web_assets.py. Do not edit.\n#pragma once\n\n#include <stddef.h>\n#include <stdint.h>\n\nnamespace web_assets {\nstruct Asset {\n    const char* path;\n    const char* contentType;\n    const char* etag;\n    const uint8_t* data;\n    size_t size;\n    bool immutable;\n};\nextern const Asset kAssets[];\nextern const size_t kAssetCount;\nextern const char kBuildId[];\n} // namespace web_assets\n"""
    lines = ["// Generated by tools/build_web_assets.py. Do not edit.", "#include \"web_assets.generated.h\"", "#include <pgmspace.h>", "", "namespace web_assets {"]
    asset_names = []
    for index, (_, _, data, _, _) in enumerate(assets):
        name = f"kAsset{index}"
        asset_names.append(name)
        lines += [f"const uint8_t {name}[] PROGMEM = {{", cpp_bytes(data), "};", ""]
    lines += ["const Asset kAssets[] = {"]
    for index, (route, content_type, data, immutable, etag) in enumerate(assets):
        lines.append(f'    {{"{route}", "{content_type}", "{etag}", {asset_names[index]}, {len(data)}, {str(immutable).lower()}}},')
    lines += ["};", "const size_t kAssetCount = sizeof(kAssets) / sizeof(kAssets[0]);", f'const char kBuildId[] = "{build_id}";', "} // namespace web_assets", ""]
    return header, "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--verify", action="store_true", help="check the generated files instead of rebuilding")
    args = parser.parse_args()
    if not args.verify:
        run_build()
    assets = collect_assets()
    header, source = generate(assets)
    if args.verify:
        if not OUT_H.exists() or not OUT_CPP.exists() or OUT_H.read_text() != header or OUT_CPP.read_text() != source:
            raise SystemExit("generated web assets are stale; run python3 tools/build_web_assets.py")
        print(f"web asset check passed: {len(assets)} files, {sum(len(a[2]) for a in assets)} compressed bytes")
        return
    OUT_H.write_text(header)
    OUT_CPP.write_text(source)
    print(f"generated {len(assets)} embedded web files ({sum(len(a[2]) for a in assets)} gzip bytes, build {hashlib.sha256(b''.join(a[2] for a in assets)).hexdigest()[:16]})")


if __name__ == "__main__":
    main()
